// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMencOdILom3ytDj0B0MVUiELfkhjCGMw',
    appId: '1:383509346664:web:aa578db80ce1aaf94c3edd',
    messagingSenderId: '383509346664',
    projectId: 'tstnew-241c6',
    authDomain: 'tstnew-241c6.firebaseapp.com',
    storageBucket: 'tstnew-241c6.firebasestorage.app',
    measurementId: 'G-93Q9P6MLMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnSUeF3CRVSrROIRbqYw0nVgbKEQmk29c',
    appId: '1:383509346664:android:9c302a9457dd07764c3edd',
    messagingSenderId: '383509346664',
    projectId: 'tstnew-241c6',
    storageBucket: 'tstnew-241c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpe_Rnsg5uqKIIOVN3mZbDMDjreFyYYh4',
    appId: '1:383509346664:ios:be772150f8473ff44c3edd',
    messagingSenderId: '383509346664',
    projectId: 'tstnew-241c6',
    storageBucket: 'tstnew-241c6.firebasestorage.app',
    iosBundleId: 'com.example.a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpe_Rnsg5uqKIIOVN3mZbDMDjreFyYYh4',
    appId: '1:383509346664:ios:be772150f8473ff44c3edd',
    messagingSenderId: '383509346664',
    projectId: 'tstnew-241c6',
    storageBucket: 'tstnew-241c6.firebasestorage.app',
    iosBundleId: 'com.example.a',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMencOdILom3ytDj0B0MVUiELfkhjCGMw',
    appId: '1:383509346664:web:94e97ee87eea18934c3edd',
    messagingSenderId: '383509346664',
    projectId: 'tstnew-241c6',
    authDomain: 'tstnew-241c6.firebaseapp.com',
    storageBucket: 'tstnew-241c6.firebasestorage.app',
    measurementId: 'G-XQFG0BL2HV',
  );
}
