import 'package:a/test.dart';
import 'package:flutter/material.dart';
import 'package:firebase_dart/firebase_dart.dart' as fd;
import 'package:firebase_dart_flutter/firebase_dart_flutter.dart';
import 'firebase_options.dart'; // generated by flutterfire CLI or manual

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Setup for firebase_dart (must be first)
  await FirebaseDartFlutter.setup(isolated: false);

  // Initialize DEFAULT app using firebase_dart's FirebaseOptions
  await fd.Firebase.initializeApp(
    options: fd.FirebaseOptions(
      apiKey: DefaultFirebaseOptions.currentPlatform.apiKey,
      appId: DefaultFirebaseOptions.currentPlatform.appId,
      messagingSenderId:
          DefaultFirebaseOptions.currentPlatform.messagingSenderId,
      projectId: DefaultFirebaseOptions.currentPlatform.projectId,
      storageBucket: DefaultFirebaseOptions.currentPlatform.storageBucket,
      authDomain: DefaultFirebaseOptions.currentPlatform.authDomain,
      measurementId: DefaultFirebaseOptions.currentPlatform.measurementId,
      databaseURL: DefaultFirebaseOptions.currentPlatform.databaseURL,
    ),
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: test(), // your screen
    );
  }
}
